set(_CATKIN_CURRENT_PACKAGE "submodbus")
set(submodbus_VERSION "0.0.0")
set(submodbus_MAINTAINER "ros <ros@todo.todo>")
set(submodbus_PACKAGE_FORMAT "2")
set(submodbus_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(submodbus_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(submodbus_BUILDTOOL_DEPENDS "catkin")
set(submodbus_BUILDTOOL_EXPORT_DEPENDS )
set(submodbus_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(submodbus_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(submodbus_TEST_DEPENDS )
set(submodbus_DOC_DEPENDS )
set(submodbus_URL_WEBSITE "")
set(submodbus_URL_BUGTRACKER "")
set(submodbus_URL_REPOSITORY "")
set(submodbus_DEPRECATED "")